name: 部署到组织 GitHub Pages

on:
  push:
    branches: [ main ] # 确保这里的分支名称与您实际使用的分支名称一致

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 添加明确的权限
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 部署到组织仓库
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: elyxira/elyxira.github.io
          branch: main
          folder: . # 如果有构建过程，改为构建输出目录
          clean: true # 清理目标分支上的旧文件