name: 组织仓库自动推送

on:
  push:
    branches:
      - main # 当main分支有提交时触发
  workflow_dispatch: # 允许手动触发

jobs:
  sync-to-github-io:
    runs-on: ubuntu-latest
    steps:
      - name: 检出源码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以便同步

      - name: 部署到组织仓库
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # 部署整个仓库
          token: ${{ secrets.GH_PAGES_TOKEN }}
          repository-name: elyxira/elyxira.github.io
          branch: main
          clean: true # 清理目标分支上的旧文件
          git-config-name: GitHub Action
          git-config-email: action@github.com
          force: true
